# Generated by Django 4.0.3 on 2022-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
