# Generated by Django 4.0 on 2021-12-22 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='related_posts', to='blog_app.categorymodel'),
        ),
    ]
