# Generated by Django 4.0.3 on 2022-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_postmodel_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
