# Generated by Django 4.0.3 on 2022-04-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_postmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
