# Generated by Django 4.0.3 on 2022-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_comment_text_commentmodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_text',
            field=models.TextField(default='', verbose_name='comment text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='excerpt',
            field=models.TextField(default='', verbose_name='Excerpt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Post status'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Post title'),
        ),
    ]
