# Generated by Django 4.0.3 on 2022-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_commentmodel_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
